In [1]:
my_list  = [1,2,3]

In [2]:
import numpy as np


In [4]:
arr = np.array(my_list)

arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [17]:
#create an identity metrix using Numpy

np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5)

array([0.26145929, 0.41037016, 0.76859359, 0.77101532, 0.22707768])

In [19]:
np.random.rand(5,5)

array([[0.27381365, 0.39904863, 0.23183561, 0.21381098, 0.54426892],
       [0.4410546 , 0.06914756, 0.27865158, 0.2398708 , 0.33257212],
       [0.08476705, 0.21127909, 0.70078656, 0.40647628, 0.5572474 ],
       [0.63237683, 0.54674458, 0.11251486, 0.38926116, 0.24064596],
       [0.47994943, 0.90539162, 0.78696721, 0.40423159, 0.45234297]])

In [22]:
np.random.randint(1,100,20)

array([56, 34, 18, 18, 41, 90, 45, 56, 43, 31, 40, 67, 46, 68,  2, 48, 37,
       24, 83, 73])

In [23]:
arr = np.arange(25)

In [24]:
ranarr= np.random.randint(0, 50,10)

In [25]:
ranarr

array([34, 16,  0, 37, 42, 37, 28, 48,  7,  0])

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
ranarr


array([34, 16,  0, 37, 42, 37, 28, 48,  7,  0])

In [28]:
ranarr.max()

48

In [29]:
ranarr.min()

0

In [30]:
ranarr.argmax()

7

In [31]:
ranarr.argmin()

2

In [32]:
arr.shape


(25,)

In [34]:
arr.dtype

dtype('int32')

In [36]:
#indexing and selection

arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [46]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [48]:
arr_2d[0,1]


10

In [51]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [53]:
#conditional selection

arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])