In [1]:
my_list  = [1,2,3]


In [2]:
import numpy as np


In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
#lunspace takes in a 3 arguments of the number of points

np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [13]:
#create an identity matrix using numpy
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(5)

array([0.98910549, 0.02684913, 0.66444911, 0.53668242, 0.29814198])

In [15]:
np.random.rand(5,5)

array([[0.20303902, 0.79105844, 0.69056104, 0.33107335, 0.19976424],
       [0.14366484, 0.9296388 , 0.47190779, 0.55473034, 0.0802484 ],
       [0.22461173, 0.61435446, 0.70981128, 0.91884747, 0.16951848],
       [0.32722835, 0.69930895, 0.51328577, 0.78331654, 0.54600106],
       [0.6187673 , 0.90152049, 0.64464985, 0.99898483, 0.87767379]])

In [18]:
#return a sample from a normal distribution
np.random.randn(4,4)

array([[-0.85987922,  1.63742809,  0.64753055,  0.68776091],
       [-0.01750798,  1.04020501,  1.40629166, -0.82788121],
       [-0.83847689, -0.37293251,  0.67106206,  0.1474904 ],
       [-0.3951128 ,  2.61724412, -0.38664915, -0.05597997]])

In [19]:
np.random.randint(1,100,10)

array([68, 26, 86,  1, 24, 56,  1, 57, 31,  9])

In [20]:
arr = np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranarr = np.random.randint(0, 50,10)

In [23]:
ranarr

array([42, 34, 47, 23, 48, 21, 22, 22, 18, 37])

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
ranarr.max()

48

In [28]:
ranarr.min()

18

In [29]:
ranarr.argmin()

8

In [30]:
arr.shape


(25,)

In [31]:
arra = np.arange(0,11)

In [32]:
arra

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arra[8]

8

In [34]:
arr[1:5]

array([1, 2, 3, 4])

In [35]:
arra[5:] = 100

In [36]:
arr_2d = np.array([[5,10,15], [20,25,30],[35,40,45]])

In [37]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [38]:
arr_2d[1][0]

20

In [39]:
arr = np.arange(1,11)

In [40]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
bool_array = arr>5

In [44]:
arr[bool_array]

array([ 6,  7,  8,  9, 10])

In [45]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])